const gameList = [
    {name: "Run 3", url: "https://www.coolmathgames.com/sites/default/files/public_games/49436/game.html"},
    {name: "Papa's Freezeria", url: "https://www.coolmathgames.com/sites/default/files/public_games/48987/game.html"},
    {name: "Suika Watermelon Game", url: "https://www.coolmathgames.com/sites/default/files/public_games/53294/game.html"},
    {name: "Tiny Fishing", url: "https://www.coolmathgames.com/sites/default/files/public_games/52971/game.html"},
    {name: "Duck Duck Clicker", url: "https://www.coolmathgames.com/sites/default/files/public_games/50916/game.html"},
    {name: "Slice Master", url: "https://www.coolmathgames.com/sites/default/files/public_games/50815/game.html"},
    {name: "Fireboy and Water Girl in the Forest Temple", url: "https://www.coolmathgames.com/sites/default/files/public_games/40034/game.html"},
    {name: "Moto X3M", url: "https://www.coolmathgames.com/sites/default/files/public_games/47685/game.html"},
    {name: "Checkers", url: "https://www.coolmathgames.com/sites/default/files/public_games/51531/game.html"},
    {name: "Dino Game", url: "https://www.coolmathgames.com/sites/default/files/public_games/51113/game.html"},
    {name: "Planet Clicker", url: "https://www.coolmathgames.com/sites/default/files/public_games/52014/game.html"},
    {name: "Appel", url: "https://www.coolmathgames.com/sites/default/files/public_games/52458/game.html"},
    {name: "Tag", url: "https://www.coolmathgames.com/sites/default/files/public_games/52751/game.html"},
    {name: "Color by Numbers: Pixel House", url: "https://www.coolmathgames.com/sites/default/files/public_games/51684/game.html"},
    {name: "Clicker Heroes", url: "https://www.coolmathgames.com/sites/default/files/public_games/49858/game.html"},
    {name: "Penalty Kick Online", url: "https://www.coolmathgames.com/sites/default/files/public_games/51559/game.html"},
    {name: "Opposite Day", url: "https://www.coolmathgames.com/sites/default/files/public_games/51159/game.html"},
    {name: "Mr. Mine", url: "https://www.coolmathgames.com/sites/default/files/public_games/48544/game.html"},
    {name: "Snake", url: "https://www.coolmathgames.com/sites/default/files/public_games/47809/game.html"},
    {name: "Idle Breakout", url: "https://www.coolmathgames.com/sites/default/files/public_games/49029/game.html"},
    {name: "Learn to Fly 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/50678/game.html"},
    {name: "TRACE", url: "https://www.coolmathgames.com/sites/default/files/public_games/42551/game.html"},
    {name: "OvO", url: "https://www.coolmathgames.com/sites/default/files/public_games/12671/game.html"},
    {name: "Bloxorz", url: "https://www.coolmathgames.com/sites/default/files/public_games/48807/game.html"},
    {name: "Dominoes", url: "https://www.coolmathgames.com/sites/default/files/public_games/50874/game.html"},
    {name: "Retro Ping Pong", url: "https://www.coolmathgames.com/sites/default/files/public_games/48387/game.html"},
    {name: "Parking Fury 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/22160/game.html"},
    {name: "World's Hardest Game", url: "https://www.coolmathgames.com/sites/default/files/public_games/48362/game.html"},
    {name: "Raccoon Retail", url: "https://www.coolmathgames.com/sites/default/files/public_games/50484/game.html"},
    {name: "Eggy Car", url: "https://www.coolmathgames.com/sites/default/files/public_games/50081/game.html"},
    {name: "Fruit Ninja", url: "https://www.coolmathgames.com/sites/default/files/public_games/50823/game.html"},
    {name: "Car Drawing Game", url: "https://www.coolmathgames.com/sites/default/files/public_games/34202/game.html"},
    {name: "Candy Clicker 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/52454/game.html"},
    {name: "Cell to Singularity: Mesozoic Valley", url: "https://www.coolmathgames.com/sites/default/files/public_games/51584/game.html"},
    {name: "SquareX", url: "https://www.coolmathgames.com/sites/default/files/public_games/49868/game.html"},
    {name: "Escape from Castle Claymount", url: "https://www.coolmathgames.com/sites/default/files/public_games/50453/game.html"},
    {name: "Open 50 Doors", url: "https://www.coolmathgames.com/sites/default/files/public_games/50148/game.html"},
    {name: "Jacksmith", url: "https://www.coolmathgames.com/sites/default/files/public_games/49634/game.html"},
    {name: "JellyCar Worlds", url: "https://www.coolmathgames.com/sites/default/files/public_games/49850/game.html"},
    {name: "Double Cheeseburger, Medium Fries", url: "https://www.coolmathgames.com/sites/default/files/public_games/12606/game.html"},
    {name: "Maze", url: "https://www.coolmathgames.com/sites/default/files/public_games/47964/game.html"},
    {name: "Curve Ball 3D", url: "https://www.coolmathgames.com/sites/default/files/public_games/47965/game.html"},
    {name: "Pou", url: "https://www.coolmathgames.com/sites/default/files/public_games/41519/game.html"},
    {name: "Catch the Candy Xmas", url: "https://www.coolmathgames.com/sites/default/files/public_games/23306/game.html"},
    {name: "Catch the Candy Halloween", url: "https://www.coolmathgames.com/sites/default/files/public_games/23305/game.html"},
    {name: "IQ Ball", url: "https://www.coolmathgames.com/sites/default/files/public_games/48381/game.html"},
    {name: "Papa's Cupcakeria", url: "https://www.coolmathgames.com/sites/default/files/public_games/49175/game.html"},
    {name: "Red Ball 4 Volume 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/49635/game.html"},
    {name: "Awesome Tanks 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/48594/game.html"},
    {name: "Atari Breakout", url: "https://www.coolmathgames.com/sites/default/files/public_games/41808/game.html"},
    {name: "Basket and Ball", url: "https://www.coolmathgames.com/sites/default/files/public_games/48476/game.html"},
    {name: "There Is No Game", url: "https://www.coolmathgames.com/sites/default/files/public_games/21597/game.html"},
    {name: "Archery World Tour", url: "https://www.coolmathgames.com/sites/default/files/public_games/47960/game.html"},
    {name: "Moto X3M Pool Party", url: "https://www.coolmathgames.com/sites/default/files/public_games/12636/game.html"},
    {name: "Red Ball 4 Volume 3", url: "https://www.coolmathgames.com/sites/default/files/public_games/49947/game.html"},
    {name: "Tail of the Dragon", url: "https://www.coolmathgames.com/sites/default/files/public_games/48203/game.html"},
    {name: "Swing Monkey", url: "https://www.coolmathgames.com/sites/default/files/public_games/48340/game.html"},
    {name: "B-Cubed", url: "https://www.coolmathgames.com/sites/default/files/public_games/48834/game.html"},
    {name: "Bob the Robber", url: "https://www.coolmathgames.com/sites/default/files/public_games/49669/game.html"},
    {name: "Duck Life", url: "https://www.coolmathgames.com/sites/default/files/public_games/48914/game.html"},
    {name: "Candy Jump", url: "https://www.coolmathgames.com/sites/default/files/public_games/12566/game.html"},
    {name: "Tic Tac Toe", url: "https://www.coolmathgames.com/sites/default/files/public_games/50954/game.html"},
    {name: "2048", url: "https://www.coolmathgames.com/sites/default/files/public_games/53448/game.html"},
    {name: "Jelly Truck", url: "https://www.coolmathgames.com/sites/default/files/public_games/48376/game.html"},
    {name: "Block the Pig", url: "https://www.coolmathgames.com/sites/default/files/public_games/48477/game.html"},
    {name: "Crazy Eights", url: "https://www.coolmathgames.com/sites/default/files/public_games/51535/game.html"},
    {name: "Handulum+", url: "https://www.coolmathgames.com/sites/default/files/public_games/25799/game.html"},
    {name: "Darts", url: "https://www.coolmathgames.com/sites/default/files/public_games/51533/game.html"},
    {name: "Mini Golf Battle Royale", url: "https://www.coolmathgames.com/sites/default/files/public_games/36184/game.html"},
    {name: "CircloO", url: "https://www.coolmathgames.com/sites/default/files/public_games/23392/game.html"},
    {name: "Apple Worm", url: "https://www.coolmathgames.com/sites/default/files/public_games/49138/game.html"},
    {name: "Parking Mania", url: "https://www.coolmathgames.com/sites/default/files/public_games/24900/game.html"},
    {name: "Defly.io", url: "https://www.coolmathgames.com/sites/default/files/public_games/12531/game.html"},
    {name: "The Sun for the Vampire", url: "https://www.coolmathgames.com/sites/default/files/public_games/22617/game.html"},
    {name: "The Sun for the Vampire 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/23465/game.html"},
    {name: "Tower of Destiny", url: "https://www.coolmathgames.com/sites/default/files/public_games/49105/game.html"},
    {name: "Sugar, Sugar 3", url: "https://www.coolmathgames.com/sites/default/files/public_games/49756/game.html"},
    {name: "Divide", url: "https://www.coolmathgames.com/sites/default/files/public_games/49071/game.html"},
    {name: "Sushi Slicer", url: "https://www.coolmathgames.com/sites/default/files/public_games/21441/game.html"},
    {name: "Awesome Tanks", url: "https://www.coolmathgames.com/sites/default/files/public_games/48573/game.html"},
    {name: "Parking Fury", url: "https://www.coolmathgames.com/sites/default/files/public_games/22159/game.html"},
    {name: "Cannon Basketball", url: "https://www.coolmathgames.com/sites/default/files/public_games/49004/game.html"},
    {name: "Cannon Basketball 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/49002/game.html"},
    {name: "Cannon Basketball 3", url: "https://www.coolmathgames.com/sites/default/files/public_games/49001/game.html"},
    {name: "Pre-Civilization Bronze Age", url: "https://www.coolmathgames.com/sites/default/files/public_games/50319/game.html"},
    {name: "Catch the Candy Mech", url: "https://www.coolmathgames.com/sites/default/files/public_games/23010/game.html"},
    {name: "Diggy", url: "https://www.coolmathgames.com/sites/default/files/public_games/49685/game.html"},
    {name: "Tiny Heist", url: "https://www.coolmathgames.com/sites/default/files/public_games/38968/game.html"},
    {name: "Catch the Candy", url: "https://www.coolmathgames.com/sites/default/files/public_games/22955/game.html"},
    {name: "Tube Master", url: "https://www.coolmathgames.com/sites/default/files/public_games/22596/game.html"},
    {name: "Jet Boy", url: "https://www.coolmathgames.com/sites/default/files/public_games/23876/game.html"},
    {name: "Slime Laboratory", url: "https://www.coolmathgames.com/sites/default/files/public_games/53088/game.html"},
    {name: "Running Round", url: "https://www.coolmathgames.com/sites/default/files/public_games/49485/game.html"},
    {name: "Jelly Escape", url: "https://www.coolmathgames.com/sites/default/files/public_games/52649/game.html"},
    {name: "Basketball Master 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/49073/game.html"},
    {name: "Slime Laboratory 2", url: "https://www.coolmathgames.com/sites/default/files/public_games/53272/game.html"},
    {name: "Don't Cross The Line", url: "https://www.coolmathgames.com/sites/default/files/public_games/21992/game.html"},
    {name: "Wheely 7: Detective", url: "https://www.coolmathgames.com/sites/default/files/public_games/52698/game.html"},
    {name: "Wheely 6: Fairytale", url: "https://www.coolmathgames.com/sites/default/files/public_games/53478/game.html"}
];
